### ISSUE TITLE
Install CTRE Phoenix Framework

### ISSUE THREAD

**Issue by Nathaniel392** [The-Charge/PlyBot2019#10]
1. Uninstall the old CTRE Phoenix Framework (Icon is a life buoy with a chicken)

2. Download "CTRE Phoenix Framework Installer 5.12.1.0 (.zip)" at [http://www.ctr-electronics.com/hro.html#product_tabs_technical_resources](http://www.ctr-electronics.com/hro.html#product_tabs_technical_resources)

3. Extract the contents anywhere and run the installer. It might be flagged as a virus, but ignore it. Click "More Info" and "Run Anyway"

4. Go through the installation process, all default settings are fine. A window might open in the background saying something failed, this is fine.

######### If a previous commit is already updated, then you can stop here #########

5. When the installation is complete, open VS Code

6. Ctrl+Shift+P, search for "Manage Vendor Libraries"

7. Click "Install new libraries (**off**line)" and click CTRE Phoenix

8. Done

**Comment by AshwinS27** [comment]
You can install CTRE framework using the link but you dont have to install it within VS code if you pull the latest commit.
