### ISSUE TITLE
Install navX Java Libraries

### ISSUE THREAD

**Issue by Nathaniel392** [The-Charge/PlyBot2019#11]
1. Open VS Code

2. Ctrl+Shift+P

3. Search "Manage Vendor Libraries"

4. Click "Install new library (**on**line)"

5. Post this link:   https://www.kauailabs.com/dist/frc/2019/navx_frc.json     and hit Enter

6. Done

**Comment by ghost** [comment]
Please check yourself off when you are finished
- [x] Shiva
- [x] Kaedon
- [x] Ashwin
- [x] Tyler
- [x] Peter
- [x] Katie
- [x] Nathaniel
- [x] Min-Gi
- [x] Heleyna
- [x] Caleb
- [x] Odin

**Comment by AshwinS27** [comment]
I pulled out of TurnNDegrees and when I tried, it said "Library already installed"..so you may not have to do this

**Comment by Kaedon2619** [comment]
This should be automatically apply with the most recent version of the master branch it may be necessary in the future when we create the final repository.
