### ISSUE TITLE
Flash roboRIO

### ISSUE THREAD

**Issue by sreeramsa** [The-Charge/PlyBot2019#17]
Once electrical gets the roboRIO ready, it needs to be initiated.

**Comment by Kaedon2619** [comment]
Steps that we found to be successful:
1. Start the Rio is safe mode by holding the reset button until the status light illuminates
2. Use the web-interface with the user: admin to updated to the firmware stored at "C:\Program Files x86\National Instruments\Shared\Firmware"
3. After the restart is complete connect through USB and use the imaging software to update the team number.
4.  Then use the image software to flash the RoboRIO.
5. Deploy new code (it will take a bit longer the first time).
