### ISSUE TITLE
Claw Subsystem (Pneumatic)

### ISSUE THREAD

**Issue by sreeramsa** [The-Charge/PlyBot2019#21]
Mechanical has yet to decide if the claw delivery system will use pneumatic solenoids or motors. Because of this, we will create one of each type. With pneumatic solenoids, they are even more unsure of how it will function. They haven't decided whether or not they will use one or two single solenoids or a double solenoid. For now, just create it with one single solenoid.

**Comment by Kaedon2619** [comment]
Has this been replaced by Holders? If so shouldn't it be closed.
