### ISSUE TITLE
Add units to names

### ISSUE THREAD

**Issue by Shalmezad** [The-Charge/PlyBot2019#38]
It's good practice to add units to variable/function/argument names so it's clear what they're using (Are we driving feet/inches? Are angles in degrees or radians? etc) and ensure that proper conversion methods are used if necessary (all java trig functions use radians. Most of WPILib uses degrees). There may be cases where units won't fit in a name nicely, in which case javadoc style comments should be used. 
If you're in doubt for the units, hover over a method (such as `ahrs.getYaw()` in DriveTrain.java) and it'll usually tell you. 

-  TurnNDegreesAbsolute.java - `m_targetAngle` and `currentAngle` (fairly certain degrees)
-  DriveTrain.java
    - `MotionMagicInit(double distance)` (fairly certain ticks)
    - `MotionMagicInit(double distance, int backVelocity, int backAcceleration)` - backVelocity is raw sensor units per 100ms, backAcceleration is raw sensor units per 100ms per second. As this would be hard to document in the name, you may want to lean towards [documenting it javadoc style](https://stackoverflow.com/a/1667395/978509).
    - `setSpeedPID(double setSpeed)` (fairly certain % max speed)
    - `getCurrent()` (fairly certain amps)
    - `getYaw()` (fairly certain degrees)
-  MathUtil.java - `calcDirection(double current, double desired)` (definitely degrees)

**Comment by sreeramsa** [comment]
This branched has not been pushed to SourceTree and thus can't be merged. Please do so before closing this issue.
