### ISSUE TITLE
Getting Digital IO through the navx

### ISSUE THREAD

**Issue by sreeramsa** [The-Charge/PlyBot2019#39]
We're running out of ports on the roboRio due to all the line following sensors. We need to figure out how we get this (the title) to work in the code.

**Comment by drakeot** [comment]
Some ideas:

	- Maybe you use the chart with "ROBORIO CHANNEL ADDRESS"
(found here: https://pdocs.kauailabs.com/navx-mxp/installation/io-expansion/)

NavX-MXP Port	MXP Pin #	Roborio Channel Address
0				DIO0		10
1				DIO1		11
2				DIO2		12
3				DIO3		13
4				DIO8		18
5				DIO9		19
6				DIO10		20
7				DIO11		21
8				DIO12		22
9				DIO13		23
					         	^^
						        This list

	- It could also just continue the port numbering from the roborio (10-19)
