### ISSUE TITLE
Climber Subsystem

### ISSUE THREAD

**Issue by sreeramsa** [The-Charge/PlyBot2019#48]
As was explained to me by Peter (mechanical lead), this will be one motor lifting up the robot. This is very likely to change over time but it would be good to have something for now.

**Comment by sreeramsa** [comment]
This is probably going to use a spark motor.

**Comment by AshwinS27** [comment]
Finished coding the climbing subsystem. Needs tuning... I don't think we will ever get the chance to use this code :(

**Comment by sreeramsa** [comment]
There's an issue on resistance repo so closing this issue.
