### ISSUE TITLE
Create FlipDrive

### ISSUE THREAD

**Issue by sreeramsa** [The-Charge/PlyBot2019#54]
This is like invert drive but in addition to making the front the back, it flips the left and right side. This is going to involve an Instant Command to flip a boolean but we need to make that boolean to have the logic in run.

**Comment by redmanpa** [comment]
Mr. Currie has shed new light on this project. Apparently, what we now called FlipDrive is what InvertDrive should be. So instead of making a new bit of logic and driveTrain + command for FlipDrive, I'm going to adapt the InvertDrive to do what it should do.
